import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { buildPreviewCatalog } from '../../src/audio-preview/catalog';
import { createQcReport, flattenEntries, inspectAudio } from '../../src/audio-preview/qc';
import type { PreviewManifest } from '../../src/audio-preview/catalog';
import process from 'node:process';
function run(command:string,args:string[]):Promise<{code:number;stderr:string}>{return new Promise((resolveRun,reject)=>{const child=spawn(command,args,{stdio:['ignore','ignore','pipe']});let stderr='';child.stderr.on('data',c=>stderr+=c);child.on('error',reject);child.on('close',code=>resolveRun({code:code??1,stderr}))})}
async function concurrent<T>(items:T[],count:number,task:(item:T)=>Promise<void>):Promise<void>{let i=0;await Promise.all(Array.from({length:count},async()=>{while(i<items.length){const item=items[i++];if(item!==undefined)await task(item)}}))}
async function main():Promise<void>{const root=resolve(process.cwd()),manifestPath=join(root,'public/audio-previews/manifest.json'),catalog=buildPreviewCatalog();const manifest=JSON.parse(await readFile(manifestPath,'utf8')) as PreviewManifest;const entries=flattenEntries(manifest),expected=flattenEntries(catalog.manifest);if(entries.length!==expected.length)throw new Error('Manifest asset count no longer matches current catalog. Rebuild previews.');const result:Record<string,Awaited<ReturnType<typeof inspectAudio>>>={};await concurrent(entries,4,async entry=>{result[entry.previewId]=await inspectAudio(join(root,'public',entry.audioPath),entry)});for(const entry of entries)entry.technicalQc=result[entry.previewId];const {report,markdown}=await createQcReport(root,manifest,entries,result);await writeFile(manifestPath,JSON.stringify(manifest,null,2)+'\n');await writeFile(join(root,'public/audio-previews/audio-preview-qc.json'),JSON.stringify(report,null,2)+'\n');await writeFile(join(root,'public/audio-previews/audio-preview-qc.md'),markdown);const pack=await run('python3',[join(root,'scripts/audio-preview/package_review.py'),root,join(root,'.artifacts/audio-preview-review.zip')]);if(pack.code!==0)throw new Error(`Could not create review ZIP: ${pack.stderr}`);console.log(markdown);if(report.technical.failed||report.technical.manifestErrors||report.musicRules.failed)process.exitCode=1}
main().catch(error=>{console.error(error);process.exitCode=1});
