export const previewRuntimeIndex = {
  "instruments": {
    "nylon-guitar": "audio-previews/instruments/nylon-guitar.mp3",
    "acoustic-guitar": "audio-previews/instruments/acoustic-guitar.mp3",
    "manouche-guitar": "audio-previews/instruments/manouche-guitar.mp3",
    "jazz-electric-guitar": "audio-previews/instruments/jazz-electric-guitar.mp3",
    "distorted-guitar": "audio-previews/instruments/distorted-guitar.mp3",
    "piano": "audio-previews/instruments/piano.mp3",
    "rhodes": "audio-previews/instruments/rhodes.mp3",
    "hammond-organ": "audio-previews/instruments/hammond-organ.mp3",
    "vibraphone": "audio-previews/instruments/vibraphone.mp3",
    "trumpet": "audio-previews/instruments/trumpet.mp3",
    "muted-trumpet": "audio-previews/instruments/muted-trumpet.mp3",
    "flugelhorn": "audio-previews/instruments/flugelhorn.mp3",
    "alto-sax": "audio-previews/instruments/alto-sax.mp3",
    "tenor-sax": "audio-previews/instruments/tenor-sax.mp3",
    "soprano-sax": "audio-previews/instruments/soprano-sax.mp3",
    "bari-sax": "audio-previews/instruments/bari-sax.mp3",
    "clarinet": "audio-previews/instruments/clarinet.mp3",
    "trombone": "audio-previews/instruments/trombone.mp3",
    "violin": "audio-previews/instruments/violin.mp3",
    "upright-bass": "audio-previews/instruments/upright-bass.mp3",
    "electric-bass": "audio-previews/instruments/electric-bass.mp3",
    "tuba": "audio-previews/instruments/tuba.mp3",
    "brush-drums": "audio-previews/instruments/brush-drums.mp3",
    "acoustic-drums": "audio-previews/instruments/acoustic-drums.mp3",
    "heavy-rock-drums": "audio-previews/instruments/heavy-rock-drums.mp3",
    "soft-shaker": "audio-previews/instruments/soft-shaker.mp3",
    "congas": "audio-previews/instruments/congas.mp3",
    "bongos": "audio-previews/instruments/bongos.mp3",
    "timbales": "audio-previews/instruments/timbales.mp3",
    "brazilian-percussion": "audio-previews/instruments/brazilian-percussion.mp3",
    "synth": "audio-previews/instruments/synth.mp3",
    "ambient-pads": "audio-previews/instruments/ambient-pads.mp3"
  },
  "behaviours": {
    "nylon-guitar::sparse, gentle phrases with generous pauses": "audio-previews/behaviours/nylon-guitar-sparse-gentle-phrases-with-generous-pauses-1.mp3",
    "nylon-guitar::soft chordal support with a light touch": "audio-previews/behaviours/nylon-guitar-soft-chordal-support-with-a-light-touch-2.mp3",
    "nylon-guitar::a relaxed, gently syncopated melody": "audio-previews/behaviours/nylon-guitar-a-relaxed-gently-syncopated-melody-3.mp3",
    "acoustic-guitar::warm fingerstyle phrases": "audio-previews/behaviours/acoustic-guitar-warm-fingerstyle-phrases-1.mp3",
    "acoustic-guitar::soft, spacious chordal support": "audio-previews/behaviours/acoustic-guitar-soft-spacious-chordal-support-2.mp3",
    "acoustic-guitar::a restrained melodic line": "audio-previews/behaviours/acoustic-guitar-a-restrained-melodic-line-3.mp3",
    "acoustic-guitar::steady la pompe rhythm-guitar chords": "audio-previews/behaviours/acoustic-guitar-steady-la-pompe-rhythm-guitar-chords-4.mp3",
    "manouche-guitar::bright, dry single-note phrases with a crisp pick attack": "audio-previews/behaviours/manouche-guitar-bright-dry-single-note-phrases-with-a-crisp-pick-attack-1.mp3",
    "manouche-guitar::short, nimble melodic responses": "audio-previews/behaviours/manouche-guitar-short-nimble-melodic-responses-2.mp3",
    "manouche-guitar::firm, compact chord voicings": "audio-previews/behaviours/manouche-guitar-firm-compact-chord-voicings-3.mp3",
    "jazz-electric-guitar::rounded single-note phrases": "audio-previews/behaviours/jazz-electric-guitar-rounded-single-note-phrases-1.mp3",
    "jazz-electric-guitar::soft chord voicings": "audio-previews/behaviours/jazz-electric-guitar-soft-chord-voicings-2.mp3",
    "jazz-electric-guitar::subtle, lyrical improvisation": "audio-previews/behaviours/jazz-electric-guitar-subtle-lyrical-improvisation-3.mp3",
    "jazz-electric-guitar::tight offbeat funk comping with clean, clipped chord accents": "audio-previews/behaviours/jazz-electric-guitar-tight-offbeat-funk-comping-with-clean-clipped-chord-accents-4.mp3",
    "jazz-electric-guitar::expressive electric-jazz improvisation with rounded single-note phrases": "audio-previews/behaviours/jazz-electric-guitar-expressive-electric-jazz-improvisation-with-rounded-single-n-5.mp3",
    "distorted-guitar::driving electric lead phrases": "audio-previews/behaviours/distorted-guitar-driving-electric-lead-phrases-1.mp3",
    "distorted-guitar::sustained amplified notes": "audio-previews/behaviours/distorted-guitar-sustained-amplified-notes-2.mp3",
    "piano::understated melodic phrases": "audio-previews/behaviours/piano-understated-melodic-phrases-1.mp3",
    "piano::soft, spacious chord voicings": "audio-previews/behaviours/piano-soft-spacious-chord-voicings-2.mp3",
    "piano::light melodic comping": "audio-previews/behaviours/piano-light-melodic-comping-3.mp3",
    "piano::crisp syncopated comping": "audio-previews/behaviours/piano-crisp-syncopated-comping-4.mp3",
    "piano::open quartal voicings held across long modal harmonies": "audio-previews/behaviours/piano-open-quartal-voicings-held-across-long-modal-harmonies-5.mp3",
    "piano::montuno-style syncopated comping where appropriate to the Latin sub-style": "audio-previews/behaviours/piano-montuno-style-syncopated-comping-where-appropriate-to-the-la-6.mp3",
    "piano::a piano montuno locked to the 2-3 clave": "audio-previews/behaviours/piano-a-piano-montuno-locked-to-the-2-3-clave-7.mp3",
    "piano::punchy blues- and gospel-inflected comping": "audio-previews/behaviours/piano-punchy-blues-and-gospel-inflected-comping-8.mp3",
    "piano::rhythmic two-beat comping beneath a collective front line": "audio-previews/behaviours/piano-rhythmic-two-beat-comping-beneath-a-collective-front-line-9.mp3",
    "rhodes::soft electric-piano chords": "audio-previews/behaviours/rhodes-soft-electric-piano-chords-1.mp3",
    "rhodes::a mellow melodic line": "audio-previews/behaviours/rhodes-a-mellow-melodic-line-2.mp3",
    "rhodes::subtle sustained harmonic colour": "audio-previews/behaviours/rhodes-subtle-sustained-harmonic-colour-3.mp3",
    "rhodes::syncopated Rhodes comping with a tight funk pocket": "audio-previews/behaviours/rhodes-syncopated-rhodes-comping-with-a-tight-funk-pocket-4.mp3",
    "hammond-organ::warm sustained chords": "audio-previews/behaviours/hammond-organ-warm-sustained-chords-1.mp3",
    "hammond-organ::a soulful lead phrase": "audio-previews/behaviours/hammond-organ-a-soulful-lead-phrase-2.mp3",
    "hammond-organ::blues- and gospel-inflected comping": "audio-previews/behaviours/hammond-organ-blues-and-gospel-inflected-comping-3.mp3",
    "vibraphone::delicate, widely spaced notes": "audio-previews/behaviours/vibraphone-delicate-widely-spaced-notes-1.mp3",
    "vibraphone::soft shimmering chord colours": "audio-previews/behaviours/vibraphone-soft-shimmering-chord-colours-2.mp3",
    "vibraphone::occasional bell-like responses": "audio-previews/behaviours/vibraphone-occasional-bell-like-responses-3.mp3",
    "trumpet::clear, lyrical phrases": "audio-previews/behaviours/trumpet-clear-lyrical-phrases-1.mp3",
    "trumpet::measured melodic improvisation": "audio-previews/behaviours/trumpet-measured-melodic-improvisation-2.mp3",
    "trumpet::short, warm responses": "audio-previews/behaviours/trumpet-short-warm-responses-3.mp3",
    "trumpet::a syncopated Latin-jazz improvisation": "audio-previews/behaviours/trumpet-a-syncopated-latin-jazz-improvisation-4.mp3",
    "trumpet::lively Jazz improvisation over a clear 2-3 clave": "audio-previews/behaviours/trumpet-lively-jazz-improvisation-over-a-clear-2-3-clave-5.mp3",
    "trumpet::bold blues-inflected jazz improvisation": "audio-previews/behaviours/trumpet-bold-blues-inflected-jazz-improvisation-6.mp3",
    "trumpet::a clear main line anchoring lively collective front-line improvisation": "audio-previews/behaviours/trumpet-a-clear-main-line-anchoring-lively-collective-front-line-imp-7.mp3",
    "muted-trumpet::intimate, soft-edged phrases": "audio-previews/behaviours/muted-trumpet-intimate-soft-edged-phrases-1.mp3",
    "muted-trumpet::subtle, conversational responses": "audio-previews/behaviours/muted-trumpet-subtle-conversational-responses-2.mp3",
    "flugelhorn::long, gentle sustained responses": "audio-previews/behaviours/flugelhorn-long-gentle-sustained-responses-1.mp3",
    "flugelhorn::warm, lyrical phrases": "audio-previews/behaviours/flugelhorn-warm-lyrical-phrases-2.mp3",
    "flugelhorn::occasional soft melodic replies": "audio-previews/behaviours/flugelhorn-occasional-soft-melodic-replies-3.mp3",
    "alto-sax::nimble but controlled melodic phrases": "audio-previews/behaviours/alto-sax-nimble-but-controlled-melodic-phrases-1.mp3",
    "alto-sax::lyrical, measured improvisation": "audio-previews/behaviours/alto-sax-lyrical-measured-improvisation-2.mp3",
    "tenor-sax::warm, breathy phrases": "audio-previews/behaviours/tenor-sax-warm-breathy-phrases-1.mp3",
    "tenor-sax::measured melodic improvisation": "audio-previews/behaviours/tenor-sax-measured-melodic-improvisation-2.mp3",
    "tenor-sax::short conversational replies": "audio-previews/behaviours/tenor-sax-short-conversational-replies-3.mp3",
    "tenor-sax::measured jazz improvisation with syncopated Latin phrasing": "audio-previews/behaviours/tenor-sax-measured-jazz-improvisation-with-syncopated-latin-phrasing-4.mp3",
    "tenor-sax::measured jazz improvisation over the 2-3 clave": "audio-previews/behaviours/tenor-sax-measured-jazz-improvisation-over-the-2-3-clave-5.mp3",
    "tenor-sax::warm, soulful blues-inflected jazz improvisation": "audio-previews/behaviours/tenor-sax-warm-soulful-blues-inflected-jazz-improvisation-6.mp3",
    "tenor-sax::a strong, soulful front-line response": "audio-previews/behaviours/tenor-sax-a-strong-soulful-front-line-response-7.mp3",
    "tenor-sax::concise, syncopated jazz improvisation over a tight funk pocket": "audio-previews/behaviours/tenor-sax-concise-syncopated-jazz-improvisation-over-a-tight-funk-pock-8.mp3",
    "soprano-sax::clear, airy melodic phrases": "audio-previews/behaviours/soprano-sax-clear-airy-melodic-phrases-1.mp3",
    "soprano-sax::a restrained, singing line": "audio-previews/behaviours/soprano-sax-a-restrained-singing-line-2.mp3",
    "bari-sax::rounded low-register support": "audio-previews/behaviours/bari-sax-rounded-low-register-support-1.mp3",
    "bari-sax::restrained ensemble voicings": "audio-previews/behaviours/bari-sax-restrained-ensemble-voicings-2.mp3",
    "clarinet::light, nimble melodic phrases": "audio-previews/behaviours/clarinet-light-nimble-melodic-phrases-1.mp3",
    "clarinet::warm, lyrical responses": "audio-previews/behaviours/clarinet-warm-lyrical-responses-2.mp3",
    "clarinet::an active upper counterline that overlaps coherently with the trumpet or cornet main line": "audio-previews/behaviours/clarinet-an-active-upper-counterline-that-overlaps-coherently-with-th-3.mp3",
    "trombone::rounded sustained harmony": "audio-previews/behaviours/trombone-rounded-sustained-harmony-1.mp3",
    "trombone::measured, warm phrases": "audio-previews/behaviours/trombone-measured-warm-phrases-2.mp3",
    "trombone::lower tailgate-style answering phrases that overlap coherently with the front line": "audio-previews/behaviours/trombone-lower-tailgate-style-answering-phrases-that-overlap-coherent-3.mp3",
    "violin::lyrical, lightly ornamented phrases": "audio-previews/behaviours/violin-lyrical-lightly-ornamented-phrases-1.mp3",
    "violin::soft sustained harmonic texture": "audio-previews/behaviours/violin-soft-sustained-harmonic-texture-2.mp3",
    "upright-bass::a simple, warm and restrained foundation": "audio-previews/behaviours/upright-bass-a-simple-warm-and-restrained-foundation-1.mp3",
    "upright-bass::a soft, even walking pulse": "audio-previews/behaviours/upright-bass-a-soft-even-walking-pulse-2.mp3",
    "upright-bass::gentle two-feel support": "audio-previews/behaviours/upright-bass-gentle-two-feel-support-3.mp3",
    "upright-bass::a clear four-beat walking bass line": "audio-previews/behaviours/upright-bass-a-clear-four-beat-walking-bass-line-4.mp3",
    "upright-bass::a grounded modal pedal tone under a repeating ostinato": "audio-previews/behaviours/upright-bass-a-grounded-modal-pedal-tone-under-a-repeating-ostinato-5.mp3",
    "upright-bass::a repeating modal ostinato": "audio-previews/behaviours/upright-bass-a-repeating-modal-ostinato-6.mp3",
    "upright-bass::a syncopated bass line supporting the Latin groove": "audio-previews/behaviours/upright-bass-a-syncopated-bass-line-supporting-the-latin-groove-7.mp3",
    "upright-bass::a tumbao-style bass line aligned to the 2-3 clave": "audio-previews/behaviours/upright-bass-a-tumbao-style-bass-line-aligned-to-the-2-3-clave-8.mp3",
    "electric-bass::a warm, restrained bass foundation": "audio-previews/behaviours/electric-bass-a-warm-restrained-bass-foundation-1.mp3",
    "electric-bass::a soft, steady groove": "audio-previews/behaviours/electric-bass-a-soft-steady-groove-2.mp3",
    "electric-bass::a syncopated electric-bass line locked to straight 16th-note accents": "audio-previews/behaviours/electric-bass-a-syncopated-electric-bass-line-locked-to-straight-16th-note-3.mp3",
    "electric-bass::a syncopated electric-bass groove supporting a straight funk-rock pulse": "audio-previews/behaviours/electric-bass-a-syncopated-electric-bass-groove-supporting-a-straight-funk-4.mp3",
    "electric-bass::a warm electric-bass line supporting the downtempo broken-beat pulse": "audio-previews/behaviours/electric-bass-a-warm-electric-bass-line-supporting-the-downtempo-broken-be-5.mp3",
    "electric-bass::deep, warm bass support in a relaxed soul-jazz pocket": "audio-previews/behaviours/electric-bass-deep-warm-bass-support-in-a-relaxed-soul-jazz-pocket-6.mp3",
    "tuba::a prominent low-brass pulse": "audio-previews/behaviours/tuba-a-prominent-low-brass-pulse-1.mp3",
    "brush-drums::a feather-light brushed pulse": "audio-previews/behaviours/brush-drums-a-feather-light-brushed-pulse-1.mp3",
    "brush-drums::subtle timekeeping with soft brush strokes": "audio-previews/behaviours/brush-drums-subtle-timekeeping-with-soft-brush-strokes-2.mp3",
    "acoustic-drums::light, controlled swing time": "audio-previews/behaviours/acoustic-drums-light-controlled-swing-time-1.mp3",
    "acoustic-drums::restrained ride-cymbal timekeeping": "audio-previews/behaviours/acoustic-drums-restrained-ride-cymbal-timekeeping-2.mp3",
    "acoustic-drums::ride-cymbal swing with clear swing eighths": "audio-previews/behaviours/acoustic-drums-ride-cymbal-swing-with-clear-swing-eighths-3.mp3",
    "acoustic-drums::open acoustic time with light ride-cymbal and tom color": "audio-previews/behaviours/acoustic-drums-open-acoustic-time-with-light-ride-cymbal-and-tom-color-4.mp3",
    "acoustic-drums::restrained acoustic time with light hand-percussion interplay": "audio-previews/behaviours/acoustic-drums-restrained-acoustic-time-with-light-hand-percussion-interpla-5.mp3",
    "acoustic-drums::a tight, restrained straight-eighth backbeat": "audio-previews/behaviours/acoustic-drums-a-tight-restrained-straight-eighth-backbeat-6.mp3",
    "acoustic-drums::a relaxed soul-jazz shuffle with a restrained, soulful backbeat": "audio-previews/behaviours/acoustic-drums-a-relaxed-soul-jazz-shuffle-with-a-restrained-soulful-backbe-7.mp3",
    "acoustic-drums::driving ride-cymbal time with strong, punchy hard-bop accents": "audio-previews/behaviours/acoustic-drums-driving-ride-cymbal-time-with-strong-punchy-hard-bop-accents-8.mp3",
    "acoustic-drums::a tight straight-16th funk pocket with a crisp, restrained backbeat": "audio-previews/behaviours/acoustic-drums-a-tight-straight-16th-funk-pocket-with-a-crisp-restrained-ba-9.mp3",
    "acoustic-drums::powerful, controlled straight funk-rock drive with asymmetrical accents": "audio-previews/behaviours/acoustic-drums-powerful-controlled-straight-funk-rock-drive-with-asymmetric-10.mp3",
    "acoustic-drums::a hybrid electronic/live broken-beat drum texture with subtle programming and light acoustic percussion, without an EDM-style drop": "audio-previews/behaviours/acoustic-drums-a-hybrid-electronic-live-broken-beat-drum-texture-with-subtl-11.mp3",
    "acoustic-drums::buoyant two-beat acoustic timekeeping with light early-swing accents": "audio-previews/behaviours/acoustic-drums-buoyant-two-beat-acoustic-timekeeping-with-light-early-swing-12.mp3",
    "heavy-rock-drums::forceful backbeat with heavy fills": "audio-previews/behaviours/heavy-rock-drums-forceful-backbeat-with-heavy-fills-1.mp3",
    "soft-shaker::a barely noticeable bossa pulse": "audio-previews/behaviours/soft-shaker-a-barely-noticeable-bossa-pulse-1.mp3",
    "soft-shaker::a soft, even rhythmic texture": "audio-previews/behaviours/soft-shaker-a-soft-even-rhythmic-texture-2.mp3",
    "soft-shaker::subtle live percussion over the programmed broken-beat pulse": "audio-previews/behaviours/soft-shaker-subtle-live-percussion-over-the-programmed-broken-beat-pulse-3.mp3",
    "congas::light, interlocking hand percussion": "audio-previews/behaviours/congas-light-interlocking-hand-percussion-1.mp3",
    "congas::interlocking conga patterns with a clave-informed pulse": "audio-previews/behaviours/congas-interlocking-conga-patterns-with-a-clave-informed-pulse-2.mp3",
    "congas::restrained interlocking hand percussion under a repeating modal motif": "audio-previews/behaviours/congas-restrained-interlocking-hand-percussion-under-a-repeating-mo-3.mp3",
    "congas::a restrained hand-percussion texture supporting the Latin groove": "audio-previews/behaviours/congas-a-restrained-hand-percussion-texture-supporting-the-latin-gr-4.mp3",
    "congas::an interlocking conga pattern that articulates the 2-3 clave": "audio-previews/behaviours/congas-an-interlocking-conga-pattern-that-articulates-the-2-3-clave-5.mp3",
    "bongos::light syncopated hand percussion": "audio-previews/behaviours/bongos-light-syncopated-hand-percussion-1.mp3",
    "timbales::crisp, syncopated Latin accents": "audio-previews/behaviours/timbales-crisp-syncopated-latin-accents-1.mp3",
    "timbales::crisp interlocking timbales accents over a syncopated Latin groove": "audio-previews/behaviours/timbales-crisp-interlocking-timbales-accents-over-a-syncopated-latin--2.mp3",
    "timbales::interlocking timbales accents around the 2-3 clave": "audio-previews/behaviours/timbales-interlocking-timbales-accents-around-the-2-3-clave-3.mp3",
    "brazilian-percussion::a restrained, soft bossa pulse": "audio-previews/behaviours/brazilian-percussion-a-restrained-soft-bossa-pulse-1.mp3",
    "synth::soft electronic harmonic colour": "audio-previews/behaviours/synth-soft-electronic-harmonic-colour-1.mp3",
    "synth::short, subtle synthesized responses": "audio-previews/behaviours/synth-short-subtle-synthesized-responses-2.mp3",
    "ambient-pads::a very quiet sustained background texture": "audio-previews/behaviours/ambient-pads-a-very-quiet-sustained-background-texture-1.mp3"
  },
  "grooves": {
    "relaxed-swing": "audio-previews/grooves/relaxed-swing.mp3",
    "soft-straight": "audio-previews/grooves/soft-straight.mp3",
    "open": "audio-previews/grooves/open.mp3",
    "slow-bossa": "audio-previews/grooves/slow-bossa.mp3",
    "soft-bossa": "audio-previews/grooves/soft-bossa.mp3",
    "bossa": "audio-previews/grooves/bossa.mp3",
    "samba-soft": "audio-previews/grooves/samba-soft.mp3",
    "light-swing": "audio-previews/grooves/light-swing.mp3",
    "medium-swing": "audio-previews/grooves/medium-swing.mp3",
    "soft-swing": "audio-previews/grooves/soft-swing.mp3",
    "walking-swing": "audio-previews/grooves/walking-swing.mp3",
    "slow-ballad": "audio-previews/grooves/slow-ballad.mp3",
    "free": "audio-previews/grooves/free.mp3",
    "modal-pulse": "audio-previews/grooves/modal-pulse.mp3",
    "waltz": "audio-previews/grooves/waltz.mp3",
    "brisk-swing": "audio-previews/grooves/brisk-swing.mp3",
    "up-tempo": "audio-previews/grooves/up-tempo.mp3",
    "brisk-straight": "audio-previews/grooves/brisk-straight.mp3",
    "smooth-straight": "audio-previews/grooves/smooth-straight.mp3",
    "light-funk": "audio-previews/grooves/light-funk.mp3",
    "latin": "audio-previews/grooves/latin.mp3",
    "samba": "audio-previews/grooves/samba.mp3",
    "afro-cuban": "audio-previews/grooves/afro-cuban.mp3",
    "son": "audio-previews/grooves/son.mp3",
    "mambo": "audio-previews/grooves/mambo.mp3",
    "manouche-swing": "audio-previews/grooves/manouche-swing.mp3",
    "la-pompe": "audio-previews/grooves/la-pompe.mp3",
    "soul-groove": "audio-previews/grooves/soul-groove.mp3",
    "shuffle": "audio-previews/grooves/shuffle.mp3",
    "hard-swing": "audio-previews/grooves/hard-swing.mp3",
    "bebop-swing": "audio-previews/grooves/bebop-swing.mp3",
    "post-bop": "audio-previews/grooves/post-bop.mp3",
    "odd-meter": "audio-previews/grooves/odd-meter.mp3",
    "funk": "audio-previews/grooves/funk.mp3",
    "broken-beat": "audio-previews/grooves/broken-beat.mp3",
    "fusion": "audio-previews/grooves/fusion.mp3",
    "downtempo": "audio-previews/grooves/downtempo.mp3",
    "two-beat": "audio-previews/grooves/two-beat.mp3",
    "march": "audio-previews/grooves/march.mp3",
    "swing": "audio-previews/grooves/swing.mp3"
  }
} as const;
