export interface PreviewInstrument { id: string; name: string; category: string; behaviours: string[] }
export interface PreviewGroove { id: string; label: string; prompt: string }
export interface MusicEvent { beat: number; pitch: number; duration: number; velocity: number }
export interface MusicTrack { name: string; instrumentId: string; program: number; channel: number; role: string; notes: MusicEvent[] }
export interface MusicSpec { id: string; category: 'instrument'|'behaviour'|'groove'; source: string; bpm: number; meter: [number,number]; bars: number; tracks: MusicTrack[]; rules: string[] }
export interface RuleResult { rule: string; ok: boolean; detail: string }
const gm: Record<string,number> = {'nylon-guitar':24,'acoustic-guitar':24,'manouche-guitar':24,'jazz-electric-guitar':26,'distorted-guitar':30,piano:0,rhodes:4,'hammond-organ':16,vibraphone:11,trumpet:56,'muted-trumpet':59,flugelhorn:56,'alto-sax':65,'tenor-sax':66,'soprano-sax':64,'bari-sax':67,clarinet:71,trombone:57,violin:40,'upright-bass':32,'electric-bass':33,tuba:58,synth:89,'ambient-pads':89,'brush-drums':0,'acoustic-drums':0,'heavy-rock-drums':0,'soft-shaker':0,congas:0,bongos:0,timbales:0,'brazilian-percussion':0};
const hash=(s:string):number=>Array.from(s).reduce((v,c)=>(v*31+c.charCodeAt(0))>>>0,7);
const note=(beat:number,pitch:number,duration=.36,velocity=76):MusicEvent=>({beat,pitch,duration,velocity});
const tr=(name:string,instrumentId:string,role:string,notes:MusicEvent[],program=gm[instrumentId]??0,channel=role==='bass'?1:role==='harmony'?2:role==='texture'?3:0):MusicTrack=>({name,instrumentId,role,notes,program,channel});
const drum=(name:string,id:string,notes:MusicEvent[]):MusicTrack=>tr(name,id,'rhythm',notes,0,9);
const chord=(beat:number,pitches:number[],duration=.34,velocity=65):MusicEvent[]=>pitches.map(p=>note(beat,p,duration,velocity));
const repeated=(events:Array<[number,number,number?]>,bars:number,stride=4):MusicEvent[]=>Array.from({length:bars},(_,bar)=>events.map(([beat,pitch,velocity=65])=>note(bar*stride+beat,pitch,.12,velocity))).flat();
const clamp=(n:number,a:number,b:number):number=>Math.max(a,Math.min(b,n));

function melody(i:PreviewInstrument,source:string,bars=4):MusicTrack {
  const seed=hash(source+i.id), base=i.category==='brass'?64:i.category==='woodwind'?62:60, scale=[0,2,4,7,9,12,14,16,19];
  const rhythm=bars<=2?[0,.75,1.75,2.5,3.5,4.75,5.5,6.5,7.5]:[0,1.5,2.5,3.5,4.75,6,7.5,9,10.5,12.5,14,15.5];
  const notes=rhythm.slice(0,Math.min(rhythm.length,bars*4)).map((beat,n)=>note(beat,base+scale[(n*3+seed%5)%scale.length]!+(n%5===4?12:0),n%3===0?.65:.34,70+n%4*2));
  return tr(i.name,i.id,'lead',notes);
}
function bassWalk(i:PreviewInstrument):MusicTrack {
  const roots=[40,43,45,47],notes:MusicEvent[]=[];
  for(let bar=0;bar<4;bar++)for(let beat=0;beat<4;beat++)notes.push(note(bar*4+beat,beat===0?roots[bar]!:clamp(roots[bar]!+[0,3,5,7][beat]!-(bar%2?12:0),28,48),.82,74));
  return tr(i.name,i.id,'bass',notes);
}
function bassMeter(i:PreviewInstrument,stride:number,bars=4):MusicTrack {const roots=[40,43,45,47],n:MusicEvent[]=[];for(let bar=0;bar<bars;bar++){const slots=stride===3?[0,1,2]:[0,1.5,2.5];for(let beat=0;beat<slots.length;beat++)n.push(note(bar*stride+slots[beat]!,roots[bar]??40,.62,70))}return tr(i.name,i.id,'bass',n)}
function melodyMeter(i:PreviewInstrument,source:string,stride:number,bars=4):MusicTrack {const seed=hash(source+i.id),base=i.category==='brass'?64:i.category==='woodwind'?62:60,scale=[0,2,4,7,9,12,14,16,19],slots=stride===3?[0,1.5,2.5]:[0,1.25,2.5];const notes=Array.from({length:bars},(_,bar)=>slots.map((at,index)=>note(bar*stride+at,base+scale[(bar*3+index+seed%5)%scale.length]!,index===0?.62:.34,70+(bar+index)%4*2))).flat();return tr(i.name,i.id,'lead',notes)}
function harmonyMeter(i:PreviewInstrument,stride:number,bars=4):MusicTrack {const pitches=i.category==='guitar'?[55,59,62]:[60,64,67],slots=stride===3?[0,1.5]:[0,2.5],notes:MusicEvent[]=[];for(let bar=0;bar<bars;bar++)for(const at of slots)notes.push(...chord(bar*stride+at,pitches,.42,62));return tr(i.name,i.id,'harmony',notes)}
function pedal(i:PreviewInstrument):MusicTrack{return tr(i.name,i.id,'bass',Array.from({length:4},(_,bar)=>note(bar*4,36,3.82,70)))}
function bassOstinato(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<4;b++)for(const [at,p] of [[0,36],[1.5,43],[2.5,36],[3.5,38]] as const)n.push(note(b*4+at,p,.42,72));return tr(i.name,i.id,'bass',n)}
function tumbao(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<4;b++)for(const [at,p] of [[1.5,40],[3.5,43]] as const)n.push(note(b*4+at,p,.38,75));return tr(i.name,i.id,'bass',n)}
function montuno(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let cycle=0;cycle<2;cycle++)for(const at of [0,1.5,2.5,4,5.5,6.5])n.push(...chord(cycle*8+at,cycle%2?[60,64,67]:[65,69,72],.23,65));return tr(i.name,i.id,'harmony',n)}
function quartal(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<4;b++)n.push(...chord(b*4,[60+(b%2?2:0),65+(b%2?2:0),70+(b%2?2:0)],3.75,60));return tr(i.name,i.id,'harmony',n)}
function comp(i:PreviewInstrument,compact=false):MusicTrack {const pitches=i.category==='guitar'?[55,59,62,66]:[60,64,67],n:MusicEvent[]=[];for(let b=0;b<4;b++)for(const at of (compact?[0,1,2,3]:[0,1.5,2.5,3.5]))n.push(...chord(b*4+at,pitches,compact?.18:.34,62));return tr(i.name,i.id,'harmony',n)}
function clave(iid:string,name:string):MusicTrack {const n:MusicEvent[]=[];for(let c=0;c<2;c++)for(const at of [1,3,4,5.5,7])n.push(note(c*8+at,75,.12,76));return drum(name,iid,n)}
function swingRide(iid:string,name:string,bars=4,meter:[number,number]=[4,4]):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<bars;b++)for(let beat=0;beat<meter[0];beat++){const at=b*meter[0]+beat;n.push(note(at,51,.12,beat%2?52:65));if(meter[0]===4)n.push(note(at+2/3,51,.1,48))}return drum(name,iid,n)}
function pompe(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<4;b++)for(let beat=0;beat<4;beat++)n.push(...chord(b*4+beat,[55,59,62,66],.16,72));return tr(i.name,i.id,'harmony',n)}
function bossaComp(i:PreviewInstrument):MusicTrack {const n:MusicEvent[]=[];for(let b=0;b<4;b++)for(const beat of [.5,1.5,2.5,3.5])n.push(...chord(b*4+beat,[55,59,62],.18,60));return tr(i.name,i.id,'harmony',n)}
function drums(pattern:string,id:string,name:string,bars=4,meter:[number,number]=[4,4]):MusicTrack {
 if(pattern==='swing-ride')return swingRide(id,name,bars,meter);
 if(pattern==='clave'||pattern==='latin-clave'||pattern.endsWith('-clave'))return clave(id,name);
 if(pattern==='jazz-waltz')return drum(name,id,repeated([[0,51,65],[1,38,47],[2,51,54]],bars,3));
 if(pattern==='odd-meter')return drum(name,id,repeated([[0,36,72],[.5,42,44],[1,42,40],[1.5,38,66],[2,42,43],[2.5,36,58],[3,38,60]],bars,3.5));
 if(pattern==='march')return drum(name,id,repeated([[0,36,70],[1,38,62],[2,36,62],[3,38,66],[.5,42,44],[1.5,42,44],[2.5,42,44],[3.5,42,44]],bars));
 if(pattern==='funk')return drum(name,id,repeated([[0,36,75],[1.5,36,56],[2.75,36,62],[1,38,68],[3,38,72],[0,42,48],[.5,42,40],[1,42,43],[1.5,42,39],[2,42,47],[2.5,42,39],[3,42,45],[3.5,42,40]],bars));
 if(pattern==='ballad'||pattern==='open'||pattern==='modal-pulse')return drum(name,id,repeated([[0,51,54],[2,38,42]],bars));
 if(pattern==='boom-bap'){const e:Array<[number,number,number?]>=[[0,36,82],[2,36,70],[1,38,78],[3,38,80]];for(let x=0;x<8;x++)e.push([x*.5,42,x%2?40:50]);return drum(name,id,repeated(e,bars))}
 if(pattern==='straight-16-funk'||pattern==='neo-soul'){const e:Array<[number,number,number?]>=[[0,36,78],[2,36,68],[1,38,74],[3,38,77]];for(let x=0;x<16;x++)e.push([x*.25,42,x%4===0?57:36]);return drum(name,id,repeated(e,bars))}
 if(pattern==='broken-beat')return drum(name,id,repeated([[0,36,77],[1.75,36,63],[3.25,36,69],[1,38,75],[2.75,38,72],[3.5,38,61],[.5,42,39],[1.5,42,42],[2.5,42,39],[3.5,42,43]],bars));
 if(['bossa','samba','tumbao'].includes(pattern)){const e:Array<[number,number,number?]>=[[0,36,66],[1.5,36,52],[2.5,38,55],[3.5,37,58],[.5,70,42],[1.5,70,44],[2.5,70,42],[3.5,70,45]];if(pattern==='samba')for(let x=0;x<8;x++)e.push([x*.5,56,48]);return drum(name,id,repeated(e,bars))}
 if(pattern==='soul-shuffle'){const e:Array<[number,number,number?]>=[[0,36,72],[2,36,65],[1,38,73],[3,38,75]];for(let b=0;b<4;b++){e.push([b,42,48],[b+2/3,42,36])}return drum(name,id,repeated(e,bars))}
 if(pattern==='two-beat')return drum(name,id,repeated([[0,36,66],[2,36,60],[1,38,48],[3,38,46],[0,51,58],[1,51,44],[2,51,52],[3,51,42]],bars));
 const e:Array<[number,number,number?]>=[[0,36,42],[2,36,40],[1,38,48],[3,38,48]];for(let x=0;x<8;x++)e.push([x*.5,42,x%2?75:85]);return drum(name,id,repeated(e,bars));
}
function percussionGuide(i:PreviewInstrument,pattern:string,bars=4):MusicTrack {
 if(['acoustic-drums','brush-drums','heavy-rock-drums'].includes(i.id))return drums(pattern==='brushes'?'soul-shuffle':pattern,i.id,i.name,bars);
 const guide=drums(pattern,'acoustic-drums','percussion guide',bars),notes=guide.notes.map((event,index)=>{let pitch=event.pitch;if(i.id==='congas')pitch=pitch===36?64:pitch===38?63:62;else if(i.id==='bongos')pitch=pitch===36?61:60;else if(i.id==='timbales')pitch=pitch===36?66:pitch===38?65:56;else if(i.id==='soft-shaker')pitch=82;else if(i.id==='brazilian-percussion')pitch=pitch===36?56:pitch===38?69:70;return{...event,pitch,velocity:Math.min(84,Math.max(46,event.velocity+(pitch===event.pitch?0:12)+(index%2?0:4)))}});
 return drum(i.name,i.id,notes);
}
function patternFor(text:string,cat:string):string {const s=text.toLowerCase();if(/pedal/.test(s))return'modal-pedal';if(/odd.?meter|asymmetrical/.test(s))return'odd-meter';if(/march/.test(s))return'march';if(/light.?funk/.test(s))return'funk';if(/modal/.test(s))return'modal-pulse';if(/ballad/.test(s))return'ballad';if(/free|open, user-defined/.test(s))return'open';if(/walking|four-beat walking/.test(s))return'walking-bass';if(/tumbao/.test(s)&&/clave/.test(s))return'tumbao-clave';if(/montuno/.test(s)&&/clave/.test(s))return'montuno-clave';if(/tumbao/.test(s))return'tumbao';if(/montuno/.test(s))return'montuno';if(/la pompe|pompe rhythm/.test(s))return'la-pompe';if(/quartal/.test(s))return'quartal-voicing';if(/pedal/.test(s))return'modal-pedal';if(/ostinato/.test(s))return'modal-ostinato';if(/afro.?cuban|latin|conga|timbales|son|mambo/.test(s))return'latin-clave';if(/swing|ride|bebop/.test(s))return'swing-ride';if(/clave/.test(s))return'clave';if(/waltz/.test(s))return'jazz-waltz';if(/bossa/.test(s))return'bossa';if(/samba/.test(s))return'samba';if(/shuffle/.test(s))return'soul-shuffle';if(/broken.?beat/.test(s))return'broken-beat';if(/boom.?bap/.test(s))return'boom-bap';if(/straight.?16|16th.?note|funk.?pocket|funk-rock/.test(s))return'straight-16-funk';if(/funk/.test(s))return'funk';if(/neo.?soul/.test(s))return'neo-soul';if(/two-beat|two beat/.test(s))return'two-beat';if(cat==='bass')return/restrained|foundation|simple/.test(s)?'bass-foundation':'bass-ostinato';if(cat==='percussion')return/brush/.test(s)?'brushes':'straight-eighth';if(cat==='guitar'&&/chord|comping|voicing/.test(s))return'guitar-comping';if(/chord|comping|voicing|harmony/.test(s)||cat==='keyboard')return'spacious-comping';if(/fingerstyle/.test(s))return'fingerstyle';if(/blues|gospel|soulful/.test(s))return'soul-blues-phrase';if(/nimble|bebop/.test(s))return'bebop-phrase';if(/response|reply|answer|conversational/.test(s))return'conversational-response';if(/sustain/.test(s))return'sustained-texture';return'lyrical-phrase'}
function tracksFor(i:PreviewInstrument,p:string,source:string):MusicTrack[]{
 if(p==='walking-bass')return[bassWalk(i)];if(p==='modal-pedal')return[pedal(i)];if(p==='modal-ostinato'||p==='bass-ostinato')return[bassOstinato(i)];if(p==='tumbao')return[tumbao(i)];if(p==='tumbao-clave')return[tumbao(i),clave('acoustic-drums','2-3 clave support')];if(p==='montuno')return[montuno(i)];if(p==='montuno-clave')return[montuno(i),clave('acoustic-drums','2-3 clave support')];if(p==='quartal-voicing')return[quartal(i)];if(p==='la-pompe')return[pompe(i)];if(p==='bossa'&&i.category==='guitar')return[bossaComp(i),drums('bossa','acoustic-drums','bossa rhythm')];if(p==='clave')return i.category==='percussion'?[percussionGuide(i,p)]:[melody(i,source),clave('acoustic-drums','2-3 clave support')];
 if(p==='jazz-waltz'||p==='odd-meter'){const stride=p==='jazz-waltz'?3:3.5;if(i.category==='percussion')return[percussionGuide(i,p,4)];if(i.category==='bass')return[bassMeter(i,stride)];if(i.category==='keyboard'||i.category==='guitar')return[harmonyMeter(i,stride)];return[melodyMeter(i,source,stride)]}
 if(['swing-ride','boom-bap','straight-16-funk','neo-soul','broken-beat','bossa','samba','soul-shuffle','two-beat','latin-clave','straight-eighth','brushes','march','funk','ballad','open','modal-pulse'].includes(p)){if(i.category==='percussion')return[percussionGuide(i,p)];return[i.category==='bass'?bassOstinato(i):melody(i,source),drums(p==='latin-clave'?'clave':p,'acoustic-drums','reference rhythm')]}
 if(p==='guitar-comping'||p==='spacious-comping')return[comp(i,p==='guitar-comping')];if(p==='fingerstyle')return[comp(i),melody(i,source)];if(p==='sustained-texture')return[tr(i.name,i.id,'texture',[note(0,60,7.7,52),note(8,65,7.7,50)])];return[melody(i,source)]
}
export function makeInstrumentSpec(i:PreviewInstrument):MusicSpec {const p=i.category==='percussion'?'straight-eighth':i.category==='bass'?'bass-foundation':'lyrical-phrase';const bassNotes=Array.from({length:8},(_,beat)=>note(beat,beat%4===0?40:beat%4===2?43:36,.82,68));const textureNotes=[note(0,60,3.8,50),note(4,65,3.8,48)];const tracks=i.category==='percussion'?[percussionGuide(i,p,2)]:i.category==='bass'?[tr(i.name,i.id,'bass',bassNotes)]:i.category==='texture'?[tr(i.name,i.id,'texture',textureNotes)]:[melody(i,i.id,2)];return{id:`instrument-${i.id}`,category:'instrument',source:p,bpm:88,meter:[4,4],bars:2,tracks,rules:['valid-meter','instrument-program',...(i.category==='bass'?['bass-register']:[])]}}
export function makeBehaviourSpec(i:PreviewInstrument,behaviour:string,index=0):MusicSpec {const p=patternFor(behaviour,i.category),tracks=tracksFor(i,p,behaviour),meter:[number,number]=p==='jazz-waltz'?[3,4]:p==='odd-meter'?[7,8]:[4,4],rules=['valid-meter','instrument-program'];const names:Record<string,string>={'walking-bass':'walking-bass','tumbao-clave':'tumbao','montuno-clave':'montuno',clave:'clave-2-3','latin-clave':'clave-2-3',tumbao:'tumbao',montuno:'montuno','la-pompe':'la-pompe','swing-ride':'swing-ride','jazz-waltz':'jazz-waltz','odd-meter':'odd-meter','boom-bap':'boom-bap','straight-16-funk':'straight-16-funk','broken-beat':'broken-beat','modal-pedal':'modal-pedal','quartal-voicing':'quartal-voicing'};if(names[p])rules.push(names[p]!);return{id:`behaviour-${i.id}-${hash(behaviour).toString(16)}-${index}`,category:'behaviour',source:p,bpm:112,meter,bars:4,tracks,rules}}
function groovePattern(g:PreviewGroove):string{const text=`${g.id} ${g.label} ${g.prompt}`;if(/walking[ -]swing/i.test(text))return'swing-ride';return patternFor(text,'percussion')}
function grooveBass(p:string):MusicTrack {const i:PreviewInstrument={id:'upright-bass',name:'Upright Bass',category:'bass',behaviours:[]};if(p==='jazz-waltz')return bassMeter(i,3);if(p==='odd-meter')return bassMeter(i,3.5);if(['tumbao','tumbao-clave','bossa','samba','latin-clave','funk'].includes(p))return p==='funk'?bassOstinato(i):tumbao(i);if(p==='modal-pedal')return pedal(i);if(['broken-beat','boom-bap','neo-soul'].includes(p))return bassOstinato({...i,id:'electric-bass',name:'Electric Bass'});return bassWalk(i)}
function grooveHarmony(p:string):MusicTrack {const guitar=['bossa','samba','la-pompe','latin-clave'].includes(p),i:PreviewInstrument=guitar?{id:'nylon-guitar',name:'Nylon Guitar',category:'guitar',behaviours:[]}:{id:'piano',name:'Piano',category:'keyboard',behaviours:[]};if(p==='jazz-waltz')return harmonyMeter(i,3);if(p==='odd-meter')return harmonyMeter(i,3.5);if(p==='montuno'||p==='montuno-clave')return montuno(i);if(p==='quartal-voicing')return quartal(i);if(p==='la-pompe')return pompe(i);if(p==='bossa')return bossaComp(i);return comp(i,guitar)}
export function makeGrooveSpec(g:PreviewGroove):MusicSpec {const p=groovePattern(g),meter:[number,number]=p==='jazz-waltz'?[3,4]:p==='odd-meter'?[7,8]:[4,4],rules=['valid-meter','groove-ensemble'];const map:Record<string,string>={'modal-pedal':'modal-pedal','tumbao-clave':'tumbao','montuno-clave':'montuno',clave:'clave-2-3','latin-clave':'clave-2-3',tumbao:'tumbao','swing-ride':'swing-ride','jazz-waltz':'jazz-waltz','odd-meter':'odd-meter','boom-bap':'boom-bap','straight-16-funk':'straight-16-funk','broken-beat':'broken-beat',montuno:'montuno','la-pompe':'la-pompe'};if(map[p])rules.push(map[p]!);if(p.endsWith('-clave'))rules.push('clave-2-3');return{id:`groove-${g.id}`,category:'groove',source:p,bpm:p==='bossa'?104:p==='samba'?116:p==='jazz-waltz'?118:p==='odd-meter'?108:112,meter,bars:4,tracks:[drums(p,'acoustic-drums',`${g.label} drums`,4,meter),grooveBass(p),grooveHarmony(p)],rules}}

const starts=(t:MusicTrack):number[]=>t.notes.map(n=>n.beat).sort((a,b)=>a-b);
const mono=(t:MusicTrack):boolean=>{const e=t.notes.flatMap(n=>[[n.beat,1] as const,[n.beat+n.duration,-1] as const]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let active=0;for(const [,d] of e){active+=d;if(active>1)return false}return true};
function drumPitches(t:MusicTrack):[number,number,number]{if(t.instrumentId==='congas')return[64,63,62];if(t.instrumentId==='bongos')return[61,60,60];if(t.instrumentId==='timbales')return[66,65,56];if(t.instrumentId==='soft-shaker')return[82,82,82];if(t.instrumentId==='brazilian-percussion')return[56,69,70];return[36,38,42]}
export function validateMusicSpec(s:MusicSpec):RuleResult[]{const r:RuleResult[]=[],add=(rule:string,ok:boolean,detail:string)=>r.push({rule,ok,detail});add('valid-meter',s.meter[0]>0&&s.meter[1]>0&&s.bars>0,`${s.meter.join('/')} × ${s.bars} bars`);add('instrument-program',s.tracks.every(t=>t.program>=0&&t.program<=127&&t.notes.every(n=>n.pitch>=0&&n.pitch<=127)),'GM program and MIDI note range');const songEnd=s.bars*s.meter[0]*4/s.meter[1];add('events-within-bars',s.tracks.every(t=>t.notes.every(n=>n.beat>=0&&n.beat+n.duration<=songEnd+1e-6)),`events end within ${songEnd} quarter-note beats`);
 if(s.rules.includes('walking-bass')){const t=s.tracks.find(x=>x.role==='bass')!,a=starts(t);add('walking-bass-meter',s.meter[0]===4&&s.meter[1]===4,'4/4 meter');add('walking-bass-register',t.notes.every(n=>n.pitch>=28&&n.pitch<=48),'E1–C3 register');add('walking-bass-monophonic',mono(t),'no overlapping notes');add('walking-bass-quarter-grid',JSON.stringify(a)===JSON.stringify(Array.from({length:16},(_,n)=>n)),'quarter note onsets across four bars');add('walking-bass-root-target',t.notes.filter(n=>n.beat%4===0).length===4,'one root target per bar')}
 if(s.rules.includes('clave-2-3')){const t=s.tracks.find(x=>x.channel===9&&x.notes.length>0),a=t?starts(t).filter(x=>x<8):[];add('clave-2-3-grid',JSON.stringify(a)===JSON.stringify([1,3,4,5.5,7]),'canonical 2-3 clave on the two-bar grid')}
 if(s.rules.includes('tumbao')){const t=s.tracks.find(x=>x.role==='bass')!,a=starts(t);add('tumbao-register',t.notes.every(n=>n.pitch>=28&&n.pitch<=48),'E1–C3 register');add('tumbao-monophonic',mono(t),'monophonic bass');add('tumbao-syncopation',a.every(x=>x%1!==0),'syncopated offbeat attacks');add('tumbao-repeat',JSON.stringify(a.slice(0,4))===JSON.stringify(a.slice(4,8).map(x=>x-8)),'repeating two-bar identity')}
 if(s.rules.includes('montuno')){const t=s.tracks.find(x=>x.role==='harmony')!,a=[...new Set(starts(t))];add('montuno-keyboard-role',['piano','rhodes','hammond-organ','vibraphone'].includes(t.instrumentId),'keyboard part');add('montuno-chord-events',t.notes.length>=18&&t.notes.some(n=>n.duration<.5),'short stacked chord attacks');add('montuno-syncopation',a.some(x=>x%1!==0),'syncopated offbeat displacement');add('montuno-repeat',a.length>=12&&a.slice(0,6).every((x,i)=>a[i+6]===x+8),'repeating two-bar figure')}
 if(s.rules.includes('la-pompe')){const t=s.tracks.find(x=>x.instrumentId.includes('guitar'))!,a=[...new Set(starts(t))];add('la-pompe-guitar',Boolean(t),'guitar program');add('la-pompe-four-beat',a.length===16&&a.every((x,i)=>x===i),'four regular attacks per 4/4 bar');add('la-pompe-articulation',t.notes.every(n=>n.duration<=.2),'short chord articulation')}
 if(s.rules.includes('swing-ride')){const t=s.tracks.find(x=>x.notes.some(n=>n.pitch===51)),a=t?starts(t):[];add('swing-ride-mapping',Boolean(t?.notes.some(n=>n.pitch===51)),'GM ride cymbal note 51');add('swing-triplet-grid',a.some(x=>Math.abs(x%1-2/3)<.01),'2:1 triplet-derived ride timing');add('swing-ride-bars',s.bars===4&&s.meter[0]===4,'four bars of 4/4')}
 if(s.rules.includes('jazz-waltz')){const t=s.tracks.find(x=>x.role==='rhythm')!;add('jazz-waltz-meter',s.meter[0]===3&&s.meter[1]===4,'3/4 meter');add('jazz-waltz-triple',starts(t).slice(0,3).join(',')==='0,1,2','three evenly spaced beats per bar')}
 if(s.rules.includes('odd-meter')){const t=s.tracks.find(x=>x.role==='rhythm');add('odd-meter-signature',s.meter[0]===7&&s.meter[1]===8,'7/8 asymmetrical meter');add('odd-meter-span',Boolean(t&&t.notes.some(n=>n.beat%3.5>=3)),'rhythm pattern spans the full 7/8 bar')}
 if(s.rules.includes('boom-bap')){const t=s.tracks.find(x=>x.channel===9&&x.notes.length>0),[kick,snare,hat]=t?drumPitches(t):[36,38,42],k=t?.notes.filter(n=>n.pitch===kick)??[],sn=t?.notes.filter(n=>n.pitch===snare)??[],h=t?.notes.filter(n=>n.pitch===hat)??[];add('boom-bap-meter',s.meter[0]===4&&s.meter[1]===4,'4/4 meter');add('boom-bap-backbeat',k.some(n=>n.beat%4===0)&&k.some(n=>n.beat%4===2)&&sn.some(n=>n.beat%4===1)&&sn.some(n=>n.beat%4===3),'kick/snare backbeat');add('boom-bap-hat-rate',h.every(n=>n.beat%0.5===0),'no hat rolls faster than eighth notes')}
 if(s.rules.includes('straight-16-funk')){const t=s.tracks.find(x=>x.channel===9&&x.notes.length>0),[kick,snare,hat]=t?drumPitches(t):[36,38,42],h=t?.notes.filter(n=>n.pitch===hat)??[],k=t?.notes.filter(n=>n.pitch===kick)??[],sn=t?.notes.filter(n=>n.pitch===snare)??[];add('straight-16-meter',s.meter[0]===4&&s.meter[1]===4,'4/4 meter');add('straight-16-grid',h.length>=64&&h.every(n=>Math.abs(n.beat*4-Math.round(n.beat*4))<1e-4),'straight sixteenth-note subdivision');add('straight-16-backbeat',sn.some(n=>n.beat%4===1)&&sn.some(n=>n.beat%4===3)&&k.some(n=>n.beat%4===0),'snare on beats 2 and 4 with kick support');add('straight-16-unswung',h.every(n=>Math.abs(n.beat*4-Math.round(n.beat*4))<1e-4),'no swung subdivision')}
 if(s.rules.includes('broken-beat')){const t=s.tracks.find(x=>x.channel===9&&x.notes.length>0),[kick,snare]=t?drumPitches(t):[36,38],k=t?.notes.filter(n=>n.pitch===kick)??[],sn=t?.notes.filter(n=>n.pitch===snare)??[],onsets=t?starts(t):[],distinctRoles=kick!==snare;const syncopated=distinctRoles&&k.length&&sn.length?k.some(n=>n.beat%4===1.75||n.beat%4===3.25)&&sn.some(n=>n.beat%4===2.75):onsets.some(n=>[.75,1.75,2.75,3.25,3.5].includes(n%4));add('broken-beat-asymmetry',Boolean(syncopated),'asymmetric syncopated kick/snare or percussion event grid');add('broken-beat-not-four-floor',distinctRoles&&k.length?k.every(n=>![1,2,3].includes(n.beat%4)):Boolean(t&&onsets.some(n=>n%4!==Math.floor(n%4))),'no four-on-the-floor kick')}
 if(s.rules.includes('modal-pedal')){const t=s.tracks.find(x=>x.role==='bass')!;add('modal-pedal-stability',t.notes.length>=4&&t.notes.every(n=>n.pitch===t.notes[0]?.pitch),'stable repeated pitch');add('modal-pedal-register',t.notes.every(n=>n.pitch>=28&&n.pitch<=48),'bass register')}
 if(s.rules.includes('quartal-voicing')){const track=s.tracks.find(t=>t.role==='harmony')!;const first=Math.min(...track.notes.map(n=>n.beat));const p=[...new Set(track.notes.filter(n=>n.beat===first).map(n=>n.pitch))].sort((a,b)=>a-b);add('quartal-intervals',p.length===3&&(p[1]! - p[0]!)===5&&(p[2]! - p[1]!)===5,'stacked perfect fourths in each opening voicing')}
 if(s.rules.includes('groove-ensemble'))add('groove-mini-ensemble',s.tracks.some(t=>t.role==='rhythm')&&s.tracks.some(t=>t.role==='bass')&&s.tracks.some(t=>t.role==='harmony'),'drums, bass and chordal instrument');return r}
function vlq(n:number):number[]{let v=Math.max(0,Math.floor(n));const o=[v&127];while((v>>=7)>0)o.unshift((v&127)|128);return o}
function chunk(type:string,d:number[]):number[]{const l=d.length;return[...Array.from(type).map(c=>c.charCodeAt(0)),l>>>24&255,l>>>16&255,l>>>8&255,l&255,...d]}
export function encodeMidi(s:MusicSpec):Uint8Array {const ppq=480,us=Math.round(60_000_000/s.bpm),tracks:number[][]=[];const conductor=[0,255,81,3,us>>>16&255,us>>>8&255,us&255,0,255,88,4,s.meter[0],Math.log2(s.meter[1]),24,8,0,255,47,0];tracks.push(chunk('MTrk',conductor));for(const t of s.tracks){const ch=t.channel%16,e:Array<{tick:number;order:number;bytes:number[]}>= [{tick:0,order:0,bytes:[192|ch,t.program&127]}];for(const n of t.notes){const a=Math.round(n.beat*ppq),b=Math.max(a+1,Math.round((n.beat+n.duration)*ppq));e.push({tick:a,order:2,bytes:[144|ch,n.pitch&127,n.velocity&127]},{tick:b,order:1,bytes:[128|ch,n.pitch&127,0]})}e.sort((a,b)=>a.tick-b.tick||a.order-b.order);const d:number[]=[];let prev=0;for(const x of e){d.push(...vlq(x.tick-prev),...x.bytes);prev=x.tick}d.push(0,255,47,0);tracks.push(chunk('MTrk',d))}const h=[77,84,104,100,0,0,0,6,0,1,tracks.length>>>8&255,tracks.length&255,1,224];return new Uint8Array([...h,...tracks.flat()])}
