import '../styles.css';
import { playSequence, togglePreview, type PlaylistItem } from './player';
import type { PreviewEntry, PreviewManifest } from './catalog';

const root=document.querySelector<HTMLElement>('#audio-preview-review')!;
const esc=(value:unknown):string=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function button(category:'instrument'|'behaviour'|'groove',key:string,name:string):string{return`<button type="button" class="preview-control" data-review-play data-preview-category="${category}" data-preview-key="${esc(key)}" data-preview-name="${esc(name)}" data-preview-idle="▶ 預覽" data-preview-stop="■ 停止" aria-label="預覽 ${esc(name)}" aria-pressed="false">▶ 預覽</button>`}
function row(e:PreviewEntry,category:'instrument'|'behaviour'|'groove',key:string):string {const q=e.technicalQc as {ok?:boolean;integratedLufs?:number|null;truePeakDbtp?:number|null;durationSeconds?:number|null}|undefined;const tech=q?.ok===true?'通過':'失敗';const musical=e.musicQcPassed?'通過':'失敗';return`<tr><td><strong>${esc(e.sourceLabel)}</strong><small>${esc(e.previewId)}</small></td><td>${esc(e.instrument??'—')}</td><td><span class="qc-pill ${e.musicQcPassed?'qc-pass':'qc-fail'}">結構 ${musical}</span><small>家族：${esc(e.semanticFamily)} → ${esc(e.pattern)} · ${esc(e.meter)} · ${e.bpm} BPM</small></td><td><span class="qc-pill ${q?.ok?'qc-pass':'qc-fail'}">技術 ${tech}</span><small>${q?.durationSeconds?.toFixed(2)??'—'} s · ${q?.integratedLufs?.toFixed(1)??'—'} LUFS · ${q?.truePeakDbtp?.toFixed(1)??'—'} dBTP</small></td><td>${button(category,key,e.sourceLabel)}</td></tr>`}
function section(title:string,summary:string,rows:string,open=false):string{return`<details class="panel audio-review-section" ${open?'open':''}><summary><strong>${title}</strong><span>${summary}</span></summary><div class="audio-review-table-wrap"><table class="audio-review-table"><thead><tr><th>目錄項目</th><th>樂器</th><th>音樂規格</th><th>技術 QC</th><th>試聽</th></tr></thead><tbody>${rows}</tbody></table></div></details>`}
async function main():Promise<void>{try{const url=new URL(`${import.meta.env.BASE_URL}audio-previews/manifest.json`,window.location.origin);const response=await fetch(url);if(!response.ok)throw new Error(`manifest ${response.status}`);const m=await response.json() as PreviewManifest;const instrumentRows=Object.entries(m.instruments).map(([key,e])=>row(e,'instrument',key)).join('');const behaviourRows=Object.entries(m.behaviours).map(([key,e])=>row(e,'behaviour',key)).join('');const grooveRows=Object.entries(m.grooves).map(([key,e])=>row(e,'groove',key)).join('');const assetCount=m.coverage.instruments.mapped+m.coverage.behaviours.mapped+m.coverage.grooves.mapped;root.innerHTML=`<div class="audio-review-shell"><header class="audio-review-header"><div><p class="eyebrow">DEVELOPMENT · AUDIO QC</p><h1>Audio Preview Review</h1><p>合成參考預覽；結構測試確認拍號、音符事件、音域與樂器映射，技術測試確認音訊檔案狀態。</p></div></header><section class="panel audio-review-summary"><div><span>樂器音色</span><strong>${m.coverage.instruments.mapped} / ${m.coverage.instruments.expected}</strong></div><div><span>演奏方式</span><strong>${m.coverage.behaviours.mapped} / ${m.coverage.behaviours.behaviourPairsExpected}</strong><small>${m.coverage.behaviours.uniqueExpected} 個英文行為字串</small></div><div><span>Groove</span><strong>${m.coverage.grooves.mapped} / ${m.coverage.grooves.expected}</strong></div><div><span>音訊檔案</span><strong>${assetCount}</strong></div></section><section class="panel audio-review-actions"><button class="button button-primary" type="button" id="play-representative">▶ 播放代表 QC 組合</button><span id="playlist-status" role="status" aria-live="polite">${m.representative.length} 段代表預覽 · 每次只播放一段</span></section>${section('樂器音色預覽',`${m.coverage.instruments.mapped}/${m.coverage.instruments.expected}`,instrumentRows,true)}${section('演奏方式預覽',`${m.coverage.behaviours.mapped}/${m.coverage.behaviours.behaviourPairsExpected} · ${m.coverage.behaviours.uniqueExpected} 個不同行為`,behaviourRows)}${section('Groove 預覽',`${m.coverage.grooves.mapped}/${m.coverage.grooves.expected}`,grooveRows)}<footer class="audio-review-footer">FluidR3 General MIDI 參考音色 · ${esc(m.format)} · 約 ${m.targetLufs} LUFS · <a href="${esc(import.meta.env.BASE_URL)}audio-previews/audio-preview-qc.md">查看 QC 報告</a> · <a href="${esc(import.meta.env.BASE_URL)}AUDIO_ASSET_LICENSES.md">授權資料</a></footer></div>`;
 const stop=(message:string)=>{const status=root.querySelector<HTMLElement>('#playlist-status');if(status)status.textContent=message};
 root.addEventListener('click',event=>{const target=event.target as HTMLElement;const play=target.closest<HTMLButtonElement>('[data-review-play]');if(play){togglePreview(play,message=>stop(message));return}if(target.closest('#play-representative')){const list:PlaylistItem[]=m.representative.map(item=>({category:item.category,key:item.key,label:item.label}));playSequence(list,(i,label)=>stop(`播放 ${i+1}/${list.length}：${label}`),()=>stop('代表 QC 組合播放完成。'),(_i,label)=>stop(`${label} 播放失敗。點擊個別預覽重試。`))}});
 }catch(error){root.innerHTML=`<section class="panel"><h1>Audio Preview QC</h1><p>QC 資料暫時無法載入：${esc(error instanceof Error?error.message:'未知錯誤')}</p><p>音訊故障不會影響 Prompt Generator。</p></section>`}}
void main();
